import os
import time
import json
import logging
import warnings
import concurrent.futures
from datetime import datetime
from typing import List, Dict, Any, Optional
from google import genai
from google.genai import types
from groq import Groq
from dotenv import load_dotenv

# Suppress warnings to keep logs clean as requested
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [%(levelname)s] - %(message)s', datefmt='%H:%M:%S')
logger = logging.getLogger("AIProjectEngine")

# --- MEMORY ---
class ProjectMemory:
    def __init__(self, user_idea: str):
        self.user_idea = user_idea
        self.project_plan: Dict = {}
        self.critique_history: List[str] = []

    def update_plan(self, new_plan: Dict):
        self.project_plan = new_plan

    def add_critique(self, critique: str):
        self.critique_history.append(critique)

# --- TOOLS ---
def create_calendar_file(events: List[Dict[str, str]]):
    filename = f"artifacts/project_timeline_{int(time.time())}.ics"
    os.makedirs("artifacts", exist_ok=True)
    
    ics_content = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//AIProjectManager//AI Agent//EN"]
    for evt in events:
        start_raw = evt.get('start_date', datetime.now().strftime('%Y%m%d'))
        start = str(start_raw) if start_raw else datetime.now().strftime('%Y%m%d')
        clean_date = start.replace("-", "").replace(" ", "T")[:8]
        ics_content.append("BEGIN:VEVENT")
        ics_content.append(f"SUMMARY:{evt.get('title')}")
        ics_content.append(f"DTSTART;VALUE=DATE:{clean_date}")
        ics_content.append(f"DESCRIPTION:{evt.get('description')}")
        ics_content.append("END:VEVENT")
    ics_content.append("END:VCALENDAR")
    
    path = os.path.join(os.getcwd(), filename)
    with open(path, "w") as f:
        f.write("\n".join(ics_content))
    return {"status": "success", "file": path, "content": "\n".join(ics_content)}

def create_markdown_doc(title: str, content: str):
    slug = title.lower().replace(' ', '_')
    filename = f"artifacts/{slug}_prd_{int(time.time())}.md"
    os.makedirs("artifacts", exist_ok=True)
    
    full_content = f"# {title}\n\nGenerated by ProjectGenesis on {datetime.now().strftime('%Y-%m-%d')}\n\n{content}"
    with open(filename, "w") as f:
        f.write(full_content)
    return {"status": "success", "file": os.path.abspath(filename), "content": full_content}

tools_map = {
    'create_calendar_file': create_calendar_file,
    'create_markdown_doc': create_markdown_doc
}

# --- AGENT RUNNER ---
def run_gemini_agent(system_prompt: str, user_prompt: str, tools=None):
    api_key = os.getenv("GOOGLE_API_KEY")
    client = genai.Client(api_key=api_key)
    
    # Passing system prompt directly as system_instruction
    config = types.GenerateContentConfig(
        system_instruction=system_prompt,
        tools=tools if tools else []
    )
    
    model_id = "gemini-2.0-flash" 
    
    response = client.models.generate_content(
        model=model_id,
        contents=user_prompt,
        config=config
    )
    
    if not response.candidates: return "Error: No candidates"
    
    parts = response.candidates[0].content.parts
    for part in parts:
        if part.function_call:
            fc = part.function_call
            if fc.name in tools_map:
                # Convert fc.args to dict properly
                args_dict = {k: v for k, v in fc.args.items()} if fc.args else {}
                return tools_map[fc.name](**args_dict)
    
    return response.text

def run_groq_agent(system_prompt: str, user_prompt: str, tools_enabled=False):
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    model = "llama-3.3-70b-versatile"
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    kwargs = {
        "model": model,
        "messages": messages,
        "temperature": 0.7,
        "max_tokens": 4096,
    }
    if "JSON" in system_prompt:
        kwargs["response_format"] = {"type": "json_object"}

    completion = client.chat.completions.create(**kwargs)
    
    res_text = completion.choices[0].message.content
    
    # Tool simulation for Groq (simple version for this demo)
    if tools_enabled:
        # We'll just parse the output if it looks like a tool call, 
        # but for this specific flow, we'll focus on the JSON roadmap generation first.
        pass
        
    return res_text

def run_agent(provider: str, agent_name: str, system_prompt: str, user_prompt: str, tools=None):
    logger.info(f"Awakening Agent: {agent_name} using {provider}...")
    try:
        if provider.lower() == "gemini":
            return run_gemini_agent(system_prompt, user_prompt, tools)
        else:
            return run_groq_agent(system_prompt, user_prompt, tools_enabled=(tools is not None))
    except Exception as e:
        logger.error(f"Agent {agent_name} error: {e}")
        return f"Error: {e}"

# --- WORKFLOW PURE LOGIC ---
def run_strategist_loop(idea: str, provider: str = "gemini") -> Dict[str, Any]:
    memory = ProjectMemory(idea)
    audit_log: List[Dict[str, Any]] = []
    
    strategist_p = "You are the Lead Tech Architect. Create a roadmap JSON: {project_name, phases:[{name, duration_days, description}]}. ONLY raw JSON."
    critic_p = "You are the Devil's Advocate. Review JSON. Reply 'APPROVE' or 'REJECT: [reason]'."
    
    feedback = "None"
    plan_text: str = ""  # Safety fallback in case every cycle errors
    for i in range(1, 4):  # 3 cycles
        plan_text_raw = run_agent(provider, "Strategist", strategist_p, f"Idea: {idea}. Feedback: {feedback}")
        if isinstance(plan_text_raw, str):
            text_val = plan_text_raw
            if "{" in text_val and "}" in text_val:
                text_val = text_val[text_val.find("{"):text_val.rfind("}")+1]
            plan_text = text_val.replace("```json", "").replace("```", "").strip()
        else:
            plan_text = json.dumps(plan_text_raw)
            
        audit_log.append({"agent": "strategist", "text": "Proposed a new roadmap reflecting " + str(idea)[:30] + "...", "cycle": i})

        critique_raw = run_agent(provider, "Critic", critic_p, f"Review: {plan_text}")
        critique = str(critique_raw)
        audit_log.append({"agent": "critic", "text": critique, "cycle": i})

        if "APPROVE" in critique.upper():
            try:
                res = json.loads(plan_text)
                res["audit_log"] = audit_log
                return res
            except json.JSONDecodeError:
                feedback = "Your previous output was invalid JSON. Fix format."
                continue
        feedback = critique

    # Fallback: return the last plan if loops exhausted
    try:
        if not plan_text:
            raise ValueError("No plan text generated")
        res = json.loads(plan_text)
        res["audit_log"] = audit_log
        return res
    except (json.JSONDecodeError, TypeError, ValueError):
        return {
            "project_name": "Generation Failed",
            "idea": idea,
            "phases": [{
                "name": "Error: Quota Exceeded or API Issue",
                "duration_days": 0,
                "description": "The AI model is currently busy or rate-limited. Please try switching to 'GROQ' or wait a few seconds and try again."
            }],
            "audit_log": audit_log,
            "error": "Failed to generate a valid plan."
        }
